<a href="https://colab.research.google.com/github/RILEY-BLUE/Deep-Learning-Reproductiton/blob/master/test_final_version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive/')
%cd gdrive/My Drive/DL-REPRODUCE/FasterRCNN/  

Mounted at /content/gdrive/
/content/gdrive/My Drive/DL-REPRODUCE/FasterRCNN


In [2]:
%tensorflow_version 2.x
import tensorflow as tf

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

Found GPU at: /device:GPU:0


In [3]:

import random
import pprint
import sys
import time
import numpy as np
from optparse import OptionParser
import pickle
import math
import cv2
import copy
from matplotlib import pyplot as plt
import tensorflow as tf
import pandas as pd
import os

from sklearn.metrics import average_precision_score

from keras import backend as K
from keras.optimizers import Adam, SGD, RMSprop
from keras.layers import Flatten, Dense, Input, Conv2D, MaxPooling2D, Dropout
from keras.layers import GlobalAveragePooling2D, GlobalMaxPooling2D, TimeDistributed
from keras.engine.topology import get_source_inputs
from keras.utils import layer_utils
from keras.utils.data_utils import get_file
from keras.objectives import categorical_crossentropy

from keras.models import Model
from keras.utils import generic_utils
from keras.engine import Layer, InputSpec
from keras import initializers, regularizers


In [4]:
#sys.path.append(".")
from train import Config

base_path = './'

test_path1 =  './almonds/' # data folder

#test_path = 'newdataset/test_annotation12345.txt' # Test data (annotation file)

#test_base_path = 'newdataset/test' # Directory to save the test images

config_output_filename = os.path.join(base_path, 'model_vgg_config.pickle')

In [5]:
with open(config_output_filename, 'rb') as f_in:
	C = pickle.load(f_in)

# turn off any data augmentation at test time
C.use_horizontal_flips = False
C.use_vertical_flips = False
C.rot_90 = False

In [6]:
def format_img_size(img, C):
	""" formats the image size based on config """
	img_min_side = float(C.im_size)
	(height,width,_) = img.shape
		
	if width <= height:
		ratio = img_min_side/width
		new_height = int(ratio * height)
		new_width = int(img_min_side)
	else:
		ratio = img_min_side/height
		new_width = int(ratio * width)
		new_height = int(img_min_side)
	img = cv2.resize(img, (new_width, new_height), interpolation=cv2.INTER_CUBIC)
	return img, ratio	

def format_img_channels(img, C):
	""" formats the image channels based on config """
	img = img[:, :, (2, 1, 0)]
	img = img.astype(np.float32)
	img[:, :, 0] -= C.img_channel_mean[0]
	img[:, :, 1] -= C.img_channel_mean[1]
	img[:, :, 2] -= C.img_channel_mean[2]
	img /= C.img_scaling_factor
	img = np.transpose(img, (2, 0, 1))
	img = np.expand_dims(img, axis=0)
	return img

def format_img(img, C):
	""" formats an image for model prediction based on config """
	img, ratio = format_img_size(img, C)
	img = format_img_channels(img, C)
	return img, ratio

# Method to transform the coordinates of the bounding box to its original size
def get_real_coordinates(ratio, x1, y1, x2, y2):

	real_x1 = int(round(x1 // ratio))
	real_y1 = int(round(y1 // ratio))
	real_x2 = int(round(x2 // ratio))
	real_y2 = int(round(y2 // ratio))

	return (real_x1, real_y1, real_x2 ,real_y2)

In [7]:
from train import *
num_features = 512 # why 512?

input_shape_img = (None, None, 3)
input_shape_features = (None, None, num_features)

img_input = Input(shape=input_shape_img)
roi_input = Input(shape=(C.num_rois, 4))
feature_map_input = Input(shape=input_shape_features)

# define the base network (VGG here, can be Resnet50, Inception, etc)
shared_layers = nn_base(img_input, trainable=True)

# define the RPN, built on the base layers
num_anchors = len(C.anchor_box_scales) * len(C.anchor_box_ratios)
rpn_layers = rpn_layer(shared_layers, num_anchors)

classifier = classifier_layer(feature_map_input, roi_input, C.num_rois, nb_classes=len(C.class_mapping))

model_rpn = Model(img_input, rpn_layers)
model_classifier_only = Model([feature_map_input, roi_input], classifier)

model_classifier = Model([feature_map_input, roi_input], classifier)

print('Loading weights from {}'.format(C.model_path))
model_rpn.load_weights(C.model_path, by_name=True)
model_classifier.load_weights(C.model_path, by_name=True)

model_rpn.compile(optimizer='sgd', loss='mse')
model_classifier.compile(optimizer='sgd', loss='mse')

Loading weights from ./model/model_frcnn_vgg.hdf5


In [8]:
class_mapping = C.class_mapping
class_mapping = {v: k for k, v in class_mapping.items()}
print(class_mapping)
class_to_color = {class_mapping[v]: np.random.randint(0, 255, 3) for v in class_mapping}

{0: 'almonds', 1: 'bg'}


In [11]:
bbox_threshold = 0.1
i = 1
test_img_names_path = os.path.join(test_path1, 'sets/test.txt')
test_img_path = os.path.join(test_path1, 'images')

with open(test_img_names_path,'r') as f:
    print('Parsing testing files')
    lines = [line.rstrip('\n') for line in f]
    for line in lines: # img_name

        # Print process
        sys.stdout.write('\r'+'idx=' + str(i))
        i += 1
        st = time.time()
        filepath = os.path.join(test_img_path, line + '.png')
        img = cv2.imread(filepath)
        X, ratio = format_img(img, C)
    
        X = np.transpose(X, (0, 2, 3, 1))

        # get output layer Y1, Y2 from the RPN and the feature maps F
        # Y1: y_rpn_cls
        # Y2: y_rpn_regr
        [Y1, Y2, F] = model_rpn.predict(X)

        # Get bboxes  
        # R.shape = (300, 4)
        R = rpn_to_roi(Y1, Y2, C, K.image_data_format(), overlap_thresh=0.2)

        # convert from (x1,y1,x2,y2) to (x,y,w,h)
        R[:, 2] -= R[:, 0]
        R[:, 3] -= R[:, 1]

        # apply the spatial pyramid pooling to the proposed regions
        bboxes = {}
        probs = {}
        for jk in range(R.shape[0]//C.num_rois + 1):
          ROIs = np.expand_dims(R[C.num_rois*jk:C.num_rois*(jk+1), :], axis=0)
          if ROIs.shape[1] == 0:
              break

          if jk == R.shape[0]//C.num_rois:
              #pad R
              curr_shape = ROIs.shape
              target_shape = (curr_shape[0],C.num_rois,curr_shape[2])
              ROIs_padded = np.zeros(target_shape).astype(ROIs.dtype)
              ROIs_padded[:, :curr_shape[1], :] = ROIs
              ROIs_padded[0, curr_shape[1]:, :] = ROIs[0, 0, :]
              ROIs = ROIs_padded

          [P_cls, P_regr] = model_classifier_only.predict([F, ROIs])

          # Calculate bboxes coordinates on resized image
          for ii in range(P_cls.shape[1]):
              # Ignore 'bg' class
              if np.max(P_cls[0, ii, :]) < bbox_threshold or np.argmax(P_cls[0, ii, :]) == (P_cls.shape[2] - 1):
                  continue

              cls_name = class_mapping[np.argmax(P_cls[0, ii, :])]

              if cls_name not in bboxes:
                  bboxes[cls_name] = []
                  probs[cls_name] = []

              (x, y, w, h) = ROIs[0, ii, :]

              cls_num = np.argmax(P_cls[0, ii, :])
              try:
                  (tx, ty, tw, th) = P_regr[0, ii, 4*cls_num:4*(cls_num+1)]
                  tx /= C.classifier_regr_std[0]
                  ty /= C.classifier_regr_std[1]
                  tw /= C.classifier_regr_std[2]
                  th /= C.classifier_regr_std[3]
                  x, y, w, h = apply_regr(x, y, w, h, tx, ty, tw, th)
              except:
                  pass
              bboxes[cls_name].append([C.rpn_stride*x, C.rpn_stride*y, C.rpn_stride*(x+w), C.rpn_stride*(y+h)])
              probs[cls_name].append(np.max(P_cls[0, ii, :]))

        all_dets = []

        for key in bboxes:
            bbox = np.array(bboxes[key])

            ## uncomment this block to generate pre-nms results
            '''
            for ijk in range(bbox.shape[0]):
                (x1, y1, x2, y2) = bbox[ijk,:]
                #det = {'x1': x1, 'x2': x2, 'y1': y1, 'y2': y2, 'class': key, 'prob': new_probs[jk]}
                #all_dets.append(det)

                # Calculate real coordinates on original image
                (real_x1, real_y1, real_x2, real_y2) = get_real_coordinates(ratio, x1, y1, x2, y2)
                
                cv2.rectangle(img,(real_x1, real_y1), (real_x2, real_y2), (int(class_to_color[key][0]), int(class_to_color[key][1]), int(class_to_color[key][2])),4)
            '''
            ## uncomment this block to generate pre-nms results   

            ## uncomment this block to generate nms (final) results
            '''
            new_boxes, new_probs = non_max_suppression_fast(bbox, np.array(probs[key]), overlap_thresh=0.3)
            #print(new_boxes.shape[0])
            for jk in range(new_boxes.shape[0]):
                (x1, y1, x2, y2) = new_boxes[jk,:]
                det = {'x1': x1, 'x2': x2, 'y1': y1, 'y2': y2, 'class': key, 'prob': new_probs[jk]}
                all_dets.append(det)

                # Calculate real coordinates on original image
                (real_x1, real_y1, real_x2, real_y2) = get_real_coordinates(ratio, x1, y1, x2, y2)
                
                cv2.rectangle(img,(real_x1, real_y1), (real_x2, real_y2), (int(class_to_color[key][0]), int(class_to_color[key][1]), int(class_to_color[key][2])),4)

                textLabel = '{}: {}'.format(key,int(100*new_probs[jk]))
                all_dets.append((key,100*new_probs[jk]))

                (retval,baseLine) = cv2.getTextSize(textLabel,cv2.FONT_HERSHEY_COMPLEX,1,1)
                textOrg = (real_x1, real_y1-0)
                
                #cv2.rectangle(img, (textOrg[0] - 5, textOrg[1]+baseLine - 5), (textOrg[0]+retval[0] + 5, textOrg[1]-retval[1] - 5), (0, 0, 0), 1)
                #cv2.rectangle(img, (textOrg[0] - 5,textOrg[1]+baseLine - 5), (textOrg[0]+retval[0] + 5, textOrg[1]-retval[1] - 5), (255, 255, 255), -1)
                #cv2.putText(img, textLabel, textOrg, cv2.FONT_HERSHEY_DUPLEX, 1, (0, 0, 0), 1)
            '''  
            ## uncomment this block to generate nms (final) results

        print('Elapsed time = {}'.format(time.time() - st))
        #print(all_dets)
        #plt.figure(figsize=(10,10))
        #plt.grid()
        #plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))
        #plt.show()


Parsing testing files
idx=1[[[0. 0. 1. 1.]
  [0. 0. 2. 1.]
  [1. 0. 2. 1.]
  [2. 0. 2. 1.]]]
[[[3. 0. 2. 1.]
  [4. 0. 2. 2.]
  [5. 0. 2. 1.]
  [6. 0. 2. 1.]]]
[[[ 7.  0.  3.  1.]
  [ 8.  0.  2.  1.]
  [11.  0.  2.  1.]
  [16.  0.  1.  1.]]]
[[[0. 0. 2. 2.]
  [0. 1. 1. 2.]
  [2. 0. 2. 2.]
  [3. 0. 2. 2.]]]
[[[3. 0. 2. 2.]
  [4. 0. 2. 2.]
  [5. 0. 2. 2.]
  [6. 0. 2. 2.]]]
[[[ 7.  0.  2.  2.]
  [ 8.  0.  2.  2.]
  [ 9.  0.  2.  2.]
  [10.  0.  2.  2.]]]
[[[11.  0.  2.  2.]
  [12.  0.  2.  2.]
  [13.  0.  2.  2.]
  [14.  0.  2.  2.]]]
[[[15.  0.  2.  2.]
  [16.  0.  1.  2.]
  [ 0.  1.  2.  2.]
  [ 0.  1.  2.  2.]]]
[[[1. 1. 2. 2.]
  [2. 0. 2. 2.]
  [3. 0. 2. 2.]
  [4. 0. 2. 2.]]]
[[[5. 1. 2. 2.]
  [6. 1. 2. 2.]
  [7. 1. 2. 2.]
  [8. 1. 2. 2.]]]
[[[ 9.  1.  2.  2.]
  [10.  1.  2.  2.]
  [11.  1.  2.  2.]
  [12.  1.  2.  2.]]]
[[[13.  1.  2.  2.]
  [14.  1.  2.  2.]
  [16.  1.  1.  2.]
  [16.  1.  1.  2.]]]
[[[0. 2. 1. 2.]
  [0. 2. 2. 2.]
  [1. 2. 1. 1.]
  [2. 2. 1. 1.]]]
[[[3. 2. 1. 1.]
  [

Exception ignored in: <function IteratorResourceDeleter.__del__ at 0x7f5a88902c20>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 535, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1264, in delete_iterator
    _ctx, "DeleteIterator", name, handle, deleter)
KeyboardInterrupt: 


[[[13. 12.  4.  4.]
  [ 0. 13.  4.  4.]
  [ 0. 13.  5.  4.]
  [ 0. 13.  6.  4.]]]
[[[ 0. 13.  7.  4.]
  [ 0. 13.  8.  4.]
  [ 1. 13.  8.  4.]
  [ 2. 13.  8.  4.]]]
[[[ 3. 13.  8.  4.]
  [ 4. 13.  8.  4.]
  [ 5. 13.  8.  4.]
  [ 6. 13.  8.  4.]]]
[[[ 7. 13.  8.  4.]
  [ 8. 13.  8.  4.]
  [ 9. 13.  8.  4.]
  [10. 13.  7.  4.]]]
[[[11. 13.  6.  4.]
  [12. 13.  5.  4.]
  [13. 13.  4.  4.]
  [ 0. 14.  4.  3.]]]
[[[ 0. 14.  5.  3.]
  [ 0. 14.  6.  3.]
  [ 0. 14.  7.  3.]
  [ 0. 14.  8.  3.]]]
[[[ 1. 14.  8.  3.]
  [ 2. 14.  8.  3.]
  [ 3. 14.  8.  3.]
  [ 4. 14.  8.  3.]]]
[[[ 5. 14.  8.  3.]
  [ 6. 14.  8.  3.]
  [ 7. 14.  8.  3.]
  [ 8. 14.  8.  3.]]]
[[[ 9. 14.  8.  3.]
  [10. 14.  7.  3.]
  [11. 14.  6.  3.]
  [12. 14.  5.  3.]]]
[[[13. 14.  4.  3.]
  [ 0. 15.  4.  2.]
  [ 0. 15.  5.  2.]
  [ 0. 15.  6.  2.]]]
[[[ 0. 15.  7.  2.]
  [ 0. 15.  8.  2.]
  [ 1. 15.  8.  2.]
  [ 2. 15.  8.  2.]]]
[[[ 3. 15.  8.  2.]
  [ 4. 15.  8.  2.]
  [ 5. 15.  8.  2.]
  [ 6. 15.  8.  2.]]]
[[[ 7. 15.  8.  

KeyboardInterrupt: ignored

In [ ]:
def get_map(pred, gt, f):
	T = {}
	P = {}
	fx, fy = f

	for bbox in gt:
		bbox['bbox_matched'] = False

	pred_probs = np.array([s['prob'] for s in pred])
	box_idx_sorted_by_prob = np.argsort(pred_probs)[::-1]

	for box_idx in box_idx_sorted_by_prob:
		pred_box = pred[box_idx]
		pred_class = pred_box['class']
		pred_x1 = pred_box['x1']
		pred_x2 = pred_box['x2']
		pred_y1 = pred_box['y1']
		pred_y2 = pred_box['y2']
		pred_prob = pred_box['prob']
		if pred_class not in P:
			P[pred_class] = []
			T[pred_class] = []
		P[pred_class].append(pred_prob)
		found_match = False

		for gt_box in gt:
			gt_class = gt_box['class']
			gt_x1 = gt_box['x1']/fx
			gt_x2 = gt_box['x2']/fx
			gt_y1 = gt_box['y1']/fy
			gt_y2 = gt_box['y2']/fy
			gt_seen = gt_box['bbox_matched']
			if gt_class != pred_class:
				continue
			if gt_seen:
				continue
			iou_map = iou((pred_x1, pred_y1, pred_x2, pred_y2), (gt_x1, gt_y1, gt_x2, gt_y2))
			if iou_map >= 0.2: # according to deep fruit paper, this is enough
				found_match = True
				gt_box['bbox_matched'] = True
				break
			else:
				continue

		T[pred_class].append(int(found_match))

	for gt_box in gt:
		if not gt_box['bbox_matched']:# and not gt_box['difficult']:
			if gt_box['class'] not in P:
				P[gt_box['class']] = []
				T[gt_box['class']] = []

			T[gt_box['class']].append(1)
			P[gt_box['class']].append(0)

	#import pdb
	#pdb.set_trace()
	return T, P

In [ ]:
def format_img_map(img, C):
	"""Format image for mAP. Resize original image to C.im_size (300 in here)

	Args:
		img: cv2 image
		C: config

	Returns:
		img: Scaled and normalized image with expanding dimension
		fx: ratio for width scaling
		fy: ratio for height scaling
	"""

	img_min_side = float(C.im_size)
	(height,width,_) = img.shape
	
	if width <= height:
		f = img_min_side/width
		new_height = int(f * height)
		new_width = int(img_min_side)
	else:
		f = img_min_side/height
		new_width = int(f * width)
		new_height = int(img_min_side)
	fx = width/float(new_width)
	fy = height/float(new_height)
	img = cv2.resize(img, (new_width, new_height), interpolation=cv2.INTER_CUBIC)
	# Change image channel from BGR to RGB
	img = img[:, :, (2, 1, 0)]
	img = img.astype(np.float32)
	img[:, :, 0] -= C.img_channel_mean[0]
	img[:, :, 1] -= C.img_channel_mean[1]
	img[:, :, 2] -= C.img_channel_mean[2]
	img /= C.img_scaling_factor
	# Change img shape from (height, width, channel) to (channel, height, width)
	img = np.transpose(img, (2, 0, 1))
	# Expand one dimension at axis 0
	# img shape becames (1, channel, height, width)
	img = np.expand_dims(img, axis=0)
	return img, fx, fy

In [ ]:
print(class_mapping)

In [ ]:
test_imgs, _, _ = get_data(test_path1)

In [ ]:

T = {}
P = {}
mAPs = []
for idx, img_data in enumerate(test_imgs):
    print('{}/{}'.format(idx,len(test_imgs)))
    st = time.time()
    filepath = img_data['filepath']

    img = cv2.imread(filepath)

    X, fx, fy = format_img_map(img, C)

    # Change X (img) shape from (1, channel, height, width) to (1, height, width, channel)
    X = np.transpose(X, (0, 2, 3, 1))

    # get the feature maps and output from the RPN
    [Y1, Y2, F] = model_rpn.predict(X)


    R = rpn_to_roi(Y1, Y2, C, K.image_data_format(), overlap_thresh=0.7)

    # convert from (x1,y1,x2,y2) to (x,y,w,h)
    R[:, 2] -= R[:, 0]
    R[:, 3] -= R[:, 1]

    # apply the spatial pyramid pooling to the proposed regions
    bboxes = {}
    probs = {}

    for jk in range(R.shape[0] // C.num_rois + 1):
        ROIs = np.expand_dims(R[C.num_rois * jk:C.num_rois * (jk + 1), :], axis=0)
        if ROIs.shape[1] == 0:
            break

        if jk == R.shape[0] // C.num_rois:
            # pad R
            curr_shape = ROIs.shape
            target_shape = (curr_shape[0], C.num_rois, curr_shape[2])
            ROIs_padded = np.zeros(target_shape).astype(ROIs.dtype)
            ROIs_padded[:, :curr_shape[1], :] = ROIs
            ROIs_padded[0, curr_shape[1]:, :] = ROIs[0, 0, :]
            ROIs = ROIs_padded

        [P_cls, P_regr] = model_classifier_only.predict([F, ROIs])

        # Calculate all classes' bboxes coordinates on resized image (300, 400)
        # Drop 'bg' classes bboxes
        for ii in range(P_cls.shape[1]):

            # If class name is 'bg', continue
            if np.argmax(P_cls[0, ii, :]) == (P_cls.shape[2] - 1):
                continue

            # Get class name
            cls_name = class_mapping[np.argmax(P_cls[0, ii, :])]

            if cls_name not in bboxes:
                bboxes[cls_name] = []
                probs[cls_name] = []

            (x, y, w, h) = ROIs[0, ii, :]

            cls_num = np.argmax(P_cls[0, ii, :])
            try:
                (tx, ty, tw, th) = P_regr[0, ii, 4 * cls_num:4 * (cls_num + 1)]
                tx /= C.classifier_regr_std[0]
                ty /= C.classifier_regr_std[1]
                tw /= C.classifier_regr_std[2]
                th /= C.classifier_regr_std[3]
                x, y, w, h = roi_helpers.apply_regr(x, y, w, h, tx, ty, tw, th)
            except:
                pass
            bboxes[cls_name].append([16 * x, 16 * y, 16 * (x + w), 16 * (y + h)])
            probs[cls_name].append(np.max(P_cls[0, ii, :]))

    all_dets = []

    for key in bboxes:
        bbox = np.array(bboxes[key])

        # Apply non-max-suppression on final bboxes to get the output bounding boxe
        new_boxes, new_probs = non_max_suppression_fast(bbox, np.array(probs[key]), overlap_thresh=0.3)
        for jk in range(new_boxes.shape[0]):
            (x1, y1, x2, y2) = new_boxes[jk, :]
            det = {'x1': x1, 'x2': x2, 'y1': y1, 'y2': y2, 'class': key, 'prob': new_probs[jk]}
            all_dets.append(det)


    print('Elapsed time = {}'.format(time.time() - st))
    t, p = get_map(all_dets, img_data['bboxes'], (fx, fy))
    for key in t.keys():
        if key not in T:
            T[key] = []
            P[key] = []
        T[key].extend(t[key])
        P[key].extend(p[key])
    all_aps = []
    for key in T.keys():
        ap = average_precision_score(T[key], P[key])
        print('{} AP: {}'.format(key, ap))
        all_aps.append(ap)
    print('mAP = {}'.format(np.mean(np.array(all_aps))))
    mAPs.append(np.mean(np.array(all_aps)))
    #print(T)
    #print(P)
    
print()
print('mean average precision:', np.mean(np.array(mAPs)))
